name: Deploy SAM application to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Steg 1: Installer Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Steg 2: Installer avhengigheter
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sam_lambda/sam-boy/generate_image/requirements.txt

      # Steg 3: Bygg SAM-applikasjonen
      - name: Build SAM application
        run: sam build -t template.yaml
        working-directory: sam_lambda/sam-boy

      # Steg 4: Deploy SAM-applikasjonen
      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --stack-name my-stack-name --capabilities CAPABILITY_IAM
        working-directory: sam_lambda/sam-boy